...@vsm

grid-columns: 1
grid-rows: 7

stage.class: stage
activity.class: activity
role.class: role
tool.class: tool
artifact.class: artifact
cost.class: cost
painpoint.class: painpoint

stage1.class: stage
activity1.class: activity
role1.class: role
tools.class: NONE
artifact1.class: artifact
cost1.class: cost
painpoint1.class: painpoint
