# common styles for value-stream map
direction: right

classes: {
  stage: {
    style.fill: "#e67e22"
    style.stroke: "#e67e22"
    style.font-color: white
    style.text-transform: uppercase
  }
  activity: {
    style.fill: "#2ecc71"
    style.stroke: "#2ecc71"
    style.font-color: white
  }
  role: {
    style.fill: "#f1c40f"
    style.stroke: "#f1c40f"
  }
  tool: {
    style.fill: "#9b59b6"
    style.stroke: "#9b59b6"
    style.font-color: white
  }
  artifact: {
    style.fill: "#3498db"
    style.stroke: "#3498db"
    style.font-color: white
  }
  cost: {
    style.fill: "#e74c3c"
    style.stroke: "#e74c3c"
    style.font-color: white
  }
  painpoint: {
    style.fill: "#95a5a6"
    style.stroke: "#95a5a6"
  }
  NONE: {
    style.opacity: 0
  }
}
