[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Anddd7", email = "anddd7@icloud.com"},
]
dependencies = [
    "diagrams>=0.23.4",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

